version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # กัปตันสามารถใส่ตัวแปรอื่นๆ เช่น MongoDB URI ไว้ตรงนี้จำลองตอนรัน Local ได้
    restart: always